/**
 * Exportações centralizadas dos tipos do módulo SocialBuffer
 */

// Re-exportar todos os tipos do arquivo principal
export * from './socialTypes';

// Re-exportações para conveniência
export type {
  SocialAccount,
  SocialAccountStatus,
  SocialPlatform,
  SocialPost,
  SocialPostStatus,
  SocialPostType,
  SocialPostContent,
  SocialPostMedia,
  SocialPostSchedule,
  SocialPostAnalytics,
  SocialPostEngagement,
  SocialPostMetrics,
  SocialPostStats,
  SocialPostReport,
  SocialPostAnalytics,
  SocialPostDashboard,
  SocialPostMonitor,
  SocialPostAlert,
  SocialPostNotification,
  SocialPostWebhook,
  SocialPostAPI,
  SocialPostIntegration,
  SocialPostSync,
  SocialPostBackup,
  SocialPostRestore,
  SocialPostMigration,
  SocialPostUpgrade,
  SocialPostDowngrade,
  SocialPostMaintenance,
  SocialPostHealth,
  SocialPostPerformance,
  SocialPostSecurity,
  SocialPostCompliance,
  SocialPostAudit,
  SocialPostLog,
  SocialPostMetrics,
  SocialPostStats,
  SocialPostReport,
  SocialPostAnalytics,
  SocialPostDashboard,
  SocialPostMonitor,
  SocialPostAlert,
  SocialPostNotification,
  SocialPostWebhook,
  SocialPostAPI,
  SocialPostIntegration,
  SocialPostSync,
  SocialPostBackup,
  SocialPostRestore,
  SocialPostMigration,
  SocialPostUpgrade,
  SocialPostDowngrade,
  SocialPostMaintenance,
  SocialPostHealth,
  SocialPostPerformance,
  SocialPostSecurity,
  SocialPostCompliance,
  SocialPostAudit
} from './socialTypes';