/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "dashboard": [],
    "settings.index": [],
    "projects.index": [],
    "projects.create": [],
    "projects.store": [],
    "projects.show": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "projects.edit": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "projects.update": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "projects.destroy": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "projects.select": [],
    "projects.switch": [],
    "projects.universe.create": [],
    "projects.universe.show": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "projects.universe.workspace": [],
    "projects.universe.toggle": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "projects.universe.stats": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "projects.universe.sync": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "leads.index": [],
    "leads.create": [],
    "leads.store": [],
    "leads.show": [
        {
            "name": "lead"
        }
    ],
    "leads.edit": [
        {
            "name": "lead"
        }
    ],
    "leads.update": [
        {
            "name": "lead"
        }
    ],
    "leads.destroy": [
        {
            "name": "lead"
        }
    ],
    "workflows.index": [],
    "workflows.create": [],
    "workflows.store": [],
    "workflows.show": [
        {
            "name": "workflow"
        }
    ],
    "workflows.edit": [
        {
            "name": "workflow"
        }
    ],
    "workflows.update": [
        {
            "name": "workflow"
        }
    ],
    "workflows.destroy": [
        {
            "name": "workflow"
        }
    ],
    "email-marketing.index": [],
    "email-marketing.create": [],
    "email-marketing.store": [],
    "email-marketing.show": [
        {
            "name": "email_marketing"
        }
    ],
    "email-marketing.edit": [
        {
            "name": "email_marketing"
        }
    ],
    "email-marketing.update": [
        {
            "name": "email_marketing"
        }
    ],
    "email-marketing.destroy": [
        {
            "name": "email_marketing"
        }
    ],
    "social-buffer.index": [],
    "social-buffer.create": [],
    "social-buffer.store": [],
    "social-buffer.show": [
        {
            "name": "social_buffer"
        }
    ],
    "social-buffer.edit": [
        {
            "name": "social_buffer"
        }
    ],
    "social-buffer.update": [
        {
            "name": "social_buffer"
        }
    ],
    "social-buffer.destroy": [
        {
            "name": "social_buffer"
        }
    ],
    "aura.index": [],
    "aura.dashboard": [],
    "aura.connections.index": [],
    "aura.chats.index": [],
    "aura.flows.index": [],
    "aura.stats.index": [],
    "ai.dashboard": [],
    "analytics.overview": [],
    "media.library": [],
    "products.index": [],
    "products.create": [],
    "products.store": [],
    "products.show": [
        {
            "name": "product"
        }
    ],
    "products.edit": [
        {
            "name": "product"
        }
    ],
    "products.update": [
        {
            "name": "product"
        }
    ],
    "products.destroy": [
        {
            "name": "product"
        }
    ],
    "adstool.dashboard": [],
    "login": [],
    "logout": [],
    "register": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "api.dashboard.stats": [],
    "api.dashboard.metrics": [],
    "api.dashboard.activities": [],
    "api.dashboard.overview": [],
    "api.dashboard.widgets": [],
    "api.dashboard.widgets.show": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.widgets.create": [],
    "api.dashboard.widgets.update": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.widgets.delete": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.widgets.refresh": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.widgets.data": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.layouts": [],
    "api.dashboard.layouts.show": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.layouts.create": [],
    "api.dashboard.layouts.update": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.layouts.delete": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.layouts.set-default": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.export": [],
    "api.dashboard.share": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.shared": [
        {
            "name": "token"
        }
    ],
    "api.dashboard.alerts": [],
    "api.dashboard.alerts.read": [
        {
            "name": "id"
        }
    ],
    "api.dashboard.alerts.read-all": [],
    "api.dashboard.subscribe": [],
    "api.dashboard.unsubscribe": [],
    "api.projects.index": [],
    "api.projects.store": [],
    "api.projects.show": [
        {
            "name": "id"
        }
    ],
    "api.projects.update": [
        {
            "name": "id"
        }
    ],
    "api.projects.destroy": [
        {
            "name": "id"
        }
    ],
    "api.projects.duplicate": [
        {
            "name": "id"
        }
    ],
    "api.projects.archive": [
        {
            "name": "id"
        }
    ],
    "api.projects.restore": [
        {
            "name": "id"
        }
    ],
    "api.projects.transfer-ownership": [
        {
            "name": "id"
        }
    ],
    "api.projects.members": [
        {
            "name": "id"
        }
    ],
    "api.projects.add-member": [
        {
            "name": "id"
        }
    ],
    "api.projects.update-member": [
        {
            "name": "id"
        },
        {
            "name": "userId"
        }
    ],
    "api.projects.remove-member": [
        {
            "name": "id"
        },
        {
            "name": "userId"
        }
    ],
    "api.projects.activities": [
        {
            "name": "id"
        }
    ],
    "api.projects.record-activity": [
        {
            "name": "id"
        }
    ],
    "api.projects.stats": [],
    "api.projects.bulk-update": [],
    "api.projects.bulk-delete": [],
    "api.projects.bulk-archive": [],
    "api.leads.index": [],
    "api.leads.store": [],
    "api.leads.show": [
        {
            "name": "id"
        }
    ],
    "api.leads.update": [
        {
            "name": "id"
        }
    ],
    "api.leads.destroy": [
        {
            "name": "id"
        }
    ],
    "api.leads.update-status": [
        {
            "name": "id"
        }
    ],
    "api.leads.update-score": [
        {
            "name": "id"
        }
    ],
    "api.leads.update-tags": [
        {
            "name": "id"
        }
    ],
    "api.leads.assign": [
        {
            "name": "id"
        }
    ],
    "api.leads.activities": [
        {
            "name": "id"
        }
    ],
    "api.leads.record-activity": [
        {
            "name": "id"
        }
    ],
    "api.leads.metrics": [],
    "api.leads.analytics": [],
    "api.leads.bulk-update": [],
    "api.leads.bulk-delete": [],
    "api.leads.bulk-update-tags": [],
    "api.leads.bulk-update-status": [],
    "api.leads.import": [],
    "api.leads.export": [],
    "api.products.index": [],
    "api.products.store": [],
    "api.products.show": [
        {
            "name": "id"
        }
    ],
    "api.products.update": [
        {
            "name": "id"
        }
    ],
    "api.products.destroy": [
        {
            "name": "id"
        }
    ],
    "api.products.duplicate": [
        {
            "name": "id"
        }
    ],
    "api.products.update-status": [
        {
            "name": "id"
        }
    ],
    "api.products.update-inventory": [
        {
            "name": "id"
        }
    ],
    "api.products.update-price": [
        {
            "name": "id"
        }
    ],
    "api.products.variations": [
        {
            "name": "productId"
        }
    ],
    "api.products.create-variation": [
        {
            "name": "productId"
        }
    ],
    "api.products.update-variation": [
        {
            "name": "productId"
        },
        {
            "name": "variationId"
        }
    ],
    "api.products.delete-variation": [
        {
            "name": "productId"
        },
        {
            "name": "variationId"
        }
    ],
    "api.products.images": [
        {
            "name": "productId"
        }
    ],
    "api.products.upload-image": [
        {
            "name": "productId"
        }
    ],
    "api.products.update-image": [
        {
            "name": "productId"
        },
        {
            "name": "imageId"
        }
    ],
    "api.products.delete-image": [
        {
            "name": "productId"
        },
        {
            "name": "imageId"
        }
    ],
    "api.products.set-primary-image": [
        {
            "name": "productId"
        },
        {
            "name": "imageId"
        }
    ],
    "api.products.reviews": [
        {
            "name": "productId"
        }
    ],
    "api.products.create-review": [
        {
            "name": "productId"
        }
    ],
    "api.products.update-review": [
        {
            "name": "productId"
        },
        {
            "name": "reviewId"
        }
    ],
    "api.products.delete-review": [
        {
            "name": "productId"
        },
        {
            "name": "reviewId"
        }
    ],
    "api.products.analytics": [
        {
            "name": "productId"
        }
    ],
    "api.products.stats": [],
    "api.products.bundles": [],
    "api.products.create-bundle": [],
    "api.products.update-bundle": [
        {
            "name": "id"
        }
    ],
    "api.products.delete-bundle": [
        {
            "name": "id"
        }
    ],
    "api.products.bulk-update": [],
    "api.products.bulk-delete": [],
    "api.products.bulk-status-update": [],
    "api.products.import": [],
    "api.products.export": [],
    "users.show": [
        {
            "name": "user"
        }
    ],
    "users.update": [
        {
            "name": "user"
        }
    ],
    "users.destroy": [
        {
            "name": "user"
        }
    ],
    "users.toggle-status": [
        {
            "name": "user"
        }
    ],
    "settings.update": [
        {
            "name": "setting"
        }
    ],
    "api.ai.generate-text": [],
    "api.ai.generate-image": [],
    "api.ai.generate-video": [],
    "api.ai.chat": [],
    "api.ai.multimodal": [],
    "api.ai.analyze-text": [],
    "api.ai.analyze-sentiment": [],
    "api.ai.translate": [],
    "api.ai.summarize": [],
    "api.ai.social-content": [],
    "api.ai.services-status": [],
    "api.ai.models": [],
    "api.ai.providers": [],
    "api.ai.test-connections": [],
    "api.ai.stats": [],
    "api.ai.history": [],
    "api.ai.history.delete": [
        {
            "name": "id"
        }
    ],
    "api.ai.validate-api-key": [],
    "api.leads.segments.index": [],
    "api.leads.segments.store": [],
    "api.leads.segments.show": [
        {
            "name": "id"
        }
    ],
    "api.leads.segments.update": [
        {
            "name": "id"
        }
    ],
    "api.leads.segments.destroy": [
        {
            "name": "id"
        }
    ],
    "api.leads.custom-fields.index": [],
    "api.leads.custom-fields.store": [],
    "api.leads.custom-fields.show": [
        {
            "name": "id"
        }
    ],
    "api.leads.custom-fields.update": [
        {
            "name": "id"
        }
    ],
    "api.leads.custom-fields.destroy": [
        {
            "name": "id"
        }
    ],
    "api.leads.categorization.index": [],
    "api.projects.projects.index": [],
    "api.projects.projects.store": [],
    "api.projects.projects.show": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "api.projects.projects.update": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "api.projects.projects.destroy": [
        {
            "name": "project",
            "binding": "id"
        }
    ],
    "api.projects.switch": [
        {
            "name": "project"
        }
    ],
    "aura.connections.store": [],
    "ai.v1.generate-text": [],
    "ai.v1.validate-api-key": [],
    "ai.v1.history": [],
    "ai.v1.delete-history": [
        {
            "name": "id"
        }
    ],
    "ai.v1.providers": [],
    "ai.v1.models": [],
    "ai.v1.services-status": [],
    "ai.v1.gemini.generate-text": [],
    "ai.v1.gemini.generate-image": [],
    "ai.v1.gemini.generate-video": [],
    "ai.v1.gemini.analyze-sentiment": [],
    "ai.v1.gemini.translate": [],
    "ai.v1.gemini.summarize": [],
    "ai.v1.chat": [],
    "ai.v1.multimodal": [],
    "ai.v1.analyze-text": [],
    "ai.v1.social-content": [],
    "ai.v1.text.generate": [],
    "ai.v1.text.analyze": [],
    "ai.v1.text.answer-question": [],
    "ai.v1.image.generate": [],
    "ai.v1.chat.send": [],
    "ai.v1.chat.conversations": [],
    "ai.v1.chat.conversation": [
        {
            "name": "id"
        }
    ],
    "ai.v1.test-connections": [],
    "api.dashboard.universe": [],
    "workflows.v1.workflows.index": [],
    "workflows.v1.workflows.store": [],
    "workflows.v1.workflows.show": [
        {
            "name": "workflow"
        }
    ],
    "workflows.v1.workflows.update": [
        {
            "name": "workflow"
        }
    ],
    "workflows.v1.workflows.destroy": [
        {
            "name": "workflow"
        }
    ],
    "workflows.v1.": [
        {
            "name": "workflowId"
        }
    ],
    "workflows.webhook.trigger": [
        {
            "name": "workflowId"
        }
    ],
    "workflows.webhook.docs": [
        {
            "name": "workflowId"
        }
    ],
    "workflows.webhook.test": [
        {
            "name": "workflowId"
        }
    ],
    "analytics.v1.": [],
    "aura.connections.show": [
        {
            "name": "connection"
        }
    ],
    "aura.connections.update": [
        {
            "name": "connection"
        }
    ],
    "aura.connections.destroy": [
        {
            "name": "connection"
        }
    ],
    "aura.connections.connect": [
        {
            "name": "connection"
        }
    ],
    "aura.connections.disconnect": [
        {
            "name": "connection"
        }
    ],
    "aura.connections.verify": [
        {
            "name": "connection"
        }
    ],
    "aura.chats.show": [
        {
            "name": "chat"
        }
    ],
    "aura.chats.messages": [
        {
            "name": "auraChat"
        }
    ],
    "aura.chats.sendMessage": [
        {
            "name": "auraChat"
        }
    ],
    "aura.chats.assign": [
        {
            "name": "auraChat"
        }
    ],
    "aura.chats.linkLead": [
        {
            "name": "auraChat"
        }
    ],
    "aura.chats.startFlow": [
        {
            "name": "auraChat"
        }
    ],
    "aura.chats.close": [
        {
            "name": "auraChat"
        }
    ],
    "aura.flows.executionLogs": [],
    "aura.users.index": [],
    "aura.webhook.whatsapp": [],
    "aura.webhooks.inbound": [],
    "email-marketing.v1.email-campaigns.sendNow": [
        {
            "name": "emailCampaign"
        }
    ],
    "email-marketing.v1.email-campaigns.schedule": [
        {
            "name": "emailCampaign"
        }
    ],
    "email-marketing.v1.email-campaigns.sendTest": [
        {
            "name": "emailCampaign"
        }
    ],
    "email-marketing.v1.email-campaigns.preview": [
        {
            "name": "emailCampaign"
        }
    ],
    "email-marketing.v1.email-campaigns.updateStatus": [
        {
            "name": "emailCampaign"
        }
    ],
    "email-marketing.v1.email-campaigns.segments.attach": [
        {
            "name": "emailCampaign"
        }
    ],
    "email-marketing.v1.email-campaigns.segments.detach": [
        {
            "name": "emailCampaign"
        }
    ],
    "email-marketing.v1.email-campaigns.index": [],
    "email-marketing.v1.email-campaigns.store": [],
    "email-marketing.v1.email-campaigns.show": [
        {
            "name": "email_campaign"
        }
    ],
    "email-marketing.v1.email-campaigns.update": [
        {
            "name": "email_campaign"
        }
    ],
    "email-marketing.v1.email-campaigns.destroy": [
        {
            "name": "email_campaign"
        }
    ],
    "leads.v1.leads.index": [],
    "leads.v1.leads.store": [],
    "leads.v1.leads.show": [
        {
            "name": "lead"
        }
    ],
    "leads.v1.leads.update": [
        {
            "name": "lead"
        }
    ],
    "leads.v1.leads.destroy": [
        {
            "name": "lead"
        }
    ]
}
}
export {};
